services:
  etl_metrics_ingest:
    build: .
    container_name: etl-metrics-ingest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TIMESCALEDB_HOST=192.168.3.155
      - PROMETHEUS_HOST=192.168.3.155
      - PROMETHEUS_PORT=9090
    networks:
      - shared_network

networks:
  shared_network:
    external: true